return {
  "Bash(awk:*)",
  "Bash(chmod:*)",
  "Bash(curl:*)",
  "Bash(docker:*)",
  "Bash(docker-compose:*)",
  "Bash(env:*)",
  "Bash(find:*)",
  "Bash(for i in:*)",
  "Bash(git add:*)",
  "Bash(git branch:*)",
  "Bash(git checkout:*)",
  "Bash(git cherry-pick:*)",
  "Bash(git commit:*)",
  "Bash(git config:*)",
  "Bash(git fetch:*)",
  "Bash(git log:*)",
  "Bash(git pull:*)",
  "Bash(git rev-parse:*)",
  "Bash(git status:*)",
  "Bash(go build:*)",
  "Bash(go doc:*)",
  "Bash(go get:*)",
  "Bash(go run:*)",
  "Bash(go test:*)",
  "Bash(go vet:*)",
  "Bash(gofmt:*)",
  "Bash(grep:*)",
  "Bash(head:*)",
  "Bash(ls:*)",
  "Bash(make:*)",
  "Bash(mkdir:*)",
  "Bash(nix:*)",
  "Bash(npm install:*)",
  "Bash(npm run:*)",
  "Bash(npm test:*)",
  "Bash(npx:*)",
  "Bash(rg:*)",
  "Bash(sed:*)",
  "Bash(tail:*)",
  "Bash(yarn:*)",
  "Bash(for i in:*)",
  "WebFetch(domain:github.com)",
  "WebFetch(domain:google.com)",
  "WebFetch(domain:localhost)",
  "WebFetch(domain:raw.githubusercontent.com)",
  "WebFetch(domain:stackoverflow.com)",
}
